- adapter/controller/cli.go
The current behavior shows broken characters.
> Fix broken display of port number on the prompt

- adapter/gateway/prompt_inputter.go
- adapter/gateway/prompt_inputter_test.go
- adapter/gateway/testdata/enum.proto
- adapter/internal/testhelper/helper.go
> refactor enum inputting

- adapter/gateway/prompt_inputter.go
- adapter/gateway/prompt_inputter_test.go
- adapter/gateway/testdata/oneof.proto
> fix oneof inputting logic

- entity/message.go
- entity/message_test.go
- entity/testdata/self.proto
> fix inf-loop related to self-referenced message

- adapter/controller/cli.go
- adapter/controller/repl.go
- adapter/controller/repl_commands.go
- adapter/controller/repl_commands_test.go
- adapter/controller/repl_completer.go
- adapter/presenter/stub.go
- config/config.go
- entity/env.go
- entity/env_test.go
- entity/header.go
- glide.lock
- main.go
- usecase/header.go
- usecase/header_test.go
- usecase/interactor.go
- usecase/port/input.go
- usecase/show.go
implemented adapter of REPL header command.  
thanks to #21, the logic related to env is implemented in it PR.
https://github.com/ktr0731/evans/issues/7
> Impl header command

- Makefile
- adapter/controller/cli.go
- adapter/controller/cli_test.go
- adapter/controller/repl.go
- adapter/update_checker/checker.go
- adapter/update_checker/checker_test.go
- adapter/update_checker/client.go
- glide.lock
- main.go
- meta/meta.go
> impl update checker

- adapter/controller/cli.go
- adapter/gateway/prompt_inputter.go
- config/config.go
- glide.lock
- meta/meta.go
- refactored logic which processes config values
- use shellstring at primitive inputting
- create a new default value, `ProtoFile`
> refactored logic which processes config values

- LICENSE
- adapter/internal/protoparser/parser.go
- adapter/internal/testhelper/helper.go
- adapter/parser/parser.go
- config/config.go
- glide.lock
- glide.yaml
- meta/meta.go
remove the protoc dependency using `jhump/protoreflect/desc/protoparse`
> use protoparse instead of protoc command

- README.md
> adjust between the content of README and proto file

- config/config.go
- meta/meta.go
- usecase/call.go
- usecase/call_test.go
> fix default header

- adapter/internal/protoparser/parser.go
- adapter/parser/parser.go
- adapter/parser/parser_test.go
- adapter/parser/testdata/importing/book.proto
- adapter/parser/testdata/importing/library.proto
- adapter/protobuf/convert_test.go
- adapter/protobuf/enum_test.go
- adapter/protobuf/field_test.go
- adapter/protobuf/message_test.go
- adapter/protobuf/oneof_field_test.go
- adapter/protobuf/primitive_test.go
- adapter/protobuf/protobuf_test.go
- adapter/protobuf/rpc_test.go
- adapter/protobuf/service_test.go
- meta/meta.go
> fix importing logic related to parser.ParseFile

- Dockerfile
- Makefile
- adapter/controller/cli.go
- adapter/controller/repl_commands.go
- adapter/controller/updater.go
- adapter/gateway/prompt_inputter.go
- adapter/presenter/stub.go
- config/config.go
- entity/env_test.go
- entity/field.go
- entity/testentity/stub.go
- tests/helper/server.go
- usecase/call_test.go
- usecase/package_test.go
- usecase/service_test.go
> introduce linters

- Dockerfile
- adapter/controller/repl.go
- adapter/gateway/prompt_inputter.go
- adapter/protobuf/enum_field.go
- adapter/protobuf/field_test.go
- adapter/protobuf/setter.go
- adapter/protobuf/testdata/repeated.proto
- meta/meta.go
> fix repeated enum logic

- adapter/controller/cli.go
- adapter/controller/cli_test.go
- config/config.go
- config/config_test.go
> fix merge config func

- adapter/controller/cli.go
- adapter/controller/updater.go
- meta/meta.go
> check whether cached latest version with current version

- Gopkg.lock
- Makefile
- adapter/controller/ui.go
- config/config.go
- entity/env_test.go
- usecase/call_test.go
GitHub Releases auto update will be failed on Linux machines.
this PR fixes it by use go-update as an internal logic instead.
> fix updater

- adapter/controller/repl.go
- adapter/controller/repl_executor.go
- meta/meta.go
c-bata/go-prompt will call `Setup` method within `Run` method. then, tty's config is changed to raw mode.
so, new change blocks execute method until Evans is finished to prevent call `Setup` method.
> block execute method until Evans is finished

- adapter/gateway/prompt_inputter.go
- adapter/protobuf/enum_field.go
- adapter/protobuf/message.go
- adapter/protobuf/message_test.go
- adapter/protobuf/testdata/circular.proto
- adapter/protobuf/testdata/self.proto
- color/color.go
- entity/message.go
- meta/meta.go
- tests/helper/prompt.go
> fix circulated fields parsing

- Gopkg.lock
- meta/meta.go
> update jhump/protoreflect to the latest

- Makefile
- README.md
- codecov.yml
- tests/e2e/cli_test.go
- tests/e2e/repl_helper.go
- add `-coverpkg` option to measure application level coverage.
> update coverage command

- .circleci/scripts/build-assets.bash
- meta/meta.go
> fix build-assets.bash

- adapter/gateway/prompt_inputter.go
> remove shellstring.Parse from inputPrimitiveField

- adapter/grpc/reflection.go
- adapter/protobuf/convert.go
- adapter/protobuf/convert_test.go
- di/dependency.go
- entity/env/env.go
- entity/env/env_test.go
- entity/grpc.go
- meta/meta.go
- tests/e2e/repl_test.go
- tests/mock/entity/mock.go
> collect message fields when using gRPC reflection mode

- .circleci/config.yml
- Makefile
For prevent to waking up OOM killer.
> Limit memory usage in CircleCI

- adapter/protobuf/convert.go
> added convert defaults

- .circleci/Dockerfile
- README.md
- tests/helper/server.go
To fix [this issue](#150), upgrade the Go version in CircleCI to the latest.
> update CircleCI config

- adapter/grpc/reflection.go
- di/dependency.go
- entity/grpc.go
- tests/e2e/cli_test.go
- tests/e2e/repl_test.go
- tests/mock/entity/mock.go
To have the right package show change the way the reflection client is used
> Change usage of Reflection to get package information for Client

- adapter/grpc/grpc.go
- adapter/inputter/prompt.go
- adapter/inputter/prompt_test.go
- adapter/inputter/testdata/circulated.proto
- config/testdata/fixtures/create_a_default_global_config_if_both_of_global_and_local_config_are_not_found.golden.toml
- logger/logger.go
- logger/logger_test.go
- meta/meta.go
- tests/helper/prompt.go
fixed #163. I appreciate @seeruk!
> fix escaping logic for circular fields

- adapter/app/app.go
- adapter/app/updater.go
- adapter/prompt/prompt.go
- adapter/repl/completer.go
- adapter/repl/executor.go
- adapter/repl/repl.go
- adapter/repl/repl_test.go
- cache/cache.go
- cache/cache_test.go
- config/config.go
- config/testdata/fixtures/create_a_default_global_config_if_both_of_global_and_local_config_are_not_found.golden.toml
- config/testdata/fixtures/load_a_global_config_if_local_config_is_not_found.golden.toml
- config/testdata/fixtures/load_a_local_config.golden.toml
- config/testdata/fixtures/will_be_apply_flags.golden.toml
- config/testdata/fixtures/will_be_apply_flags_but_local_config_doesnt_exist.golden.toml
- logger/logger.go
- tests/e2e/e2e_test.go
- tests/helper/prompt.go
> implement REPL command history

- adapter/grpc/grpc.go
If the current client connection is failed for reason such as the server closed, Evans tries to reset the current connection and connect again.
> reset if connection state is transient failure

- config/testdata/fixtures/create_a_default_global_config_if_both_of_global_and_local_config_are_not_found.golden.toml
- meta/meta.go
- mode/repl.go
> handle dropped error correctly

- go.mod
- go.sum
- grpc/grpc.go
> fix an error handling

- README.md
- config/testdata/fixtures/create_a_default_global_config_if_both_of_global_and_local_config_are_not_found.golden.toml
- grpc/compressor.go
- meta/meta.go
Enable gzip compressing. Fixed #187.
> enable gzip compressor

- app/flag.go
- app/flag_test.go
- config/testdata/fixtures/create_a_default_global_config_if_both_of_global_and_local_config_are_not_found.golden.toml
- e2e/cli_test.go
- e2e/old_cli_test.go
- meta/meta.go
> fix to parse "=" of a header correctly

- cache/history.go
- mode/repl.go
- mode/repl_test.go
- prompt/prompt.go
This change fixes #191, the command history to work correctly.
> fix command history

- README.md
correct `cli call` to `cli --call`
> correct document

- go.mod
- go.sum
> fix to send header correctly against to gRPC-Web server

- fill/proto/interactive_filler.go
- prompt/prompt.go
> fix --dig-manually skip (#554)
