ktr0731/evans

config/config.go
main.go

if pwd is not git repository, doesn't read local config file

fix config init

---

adapter/gateway/prompt_inputter.go
adapter/gateway/prompt_inputter_test.go
entity/testentity/stub.go

- if an inputting field is repeated, show `<repeated>` string to prefix
- show field name instead of message name

modify ancestor name

---

adapter/controller/cli.go
adapter/controller/cli_test.go
config/config.go
glide.lock
main.go

``` sh
$ export GOPATH=/Users/foo/.ghq
```
``` toml
[default]
protoPath = ["$GOPATH/src"] # "/Users/foo/.ghq/src"
```

accepts multi paths

---

adapter/gateway/prompt_inputter.go
adapter/gateway/prompt_inputter_test.go
glide.lock

- update c-bata/go-prompt to v0.2.0
- thanks for a new feature, live prefix, don't need to tricky technique.

follow latest go-prompt

---

Makefile
adapter/controller/cli.go

I'm facing this panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x156b17a]
goroutine 19 [running]:
github.com/ktr0731/evans/adapter/controller.(*CLI).Run.func1(0xc42036a5d0, 0x1784000, 0xc4202f3400, 0xc4202f04b8)
/path/to/go/src/github.com/ktr0731/evans/adapter/controller/cli.go:134 +0x7a
created by github.com/ktr0731/evans/adapter/controller.(*CLI).Run
/path/to/go/src/github.com/ktr0731/evans/adapter/controller/cli.go:129 +0x3f9
```
and fixed it.

Fix a panic caused by nil pointer

---

adapter/internal/protoparser/parser.go
adapter/parser/parser_test.go
adapter/protobuf/message_test.go
di/dependency.go
di/dependency_test.go

This behavior was incorrect and led to strange behaviors. Proto files are meant
to be importable using hierarchical names which should be found relative to the
import paths. Hence, adding the directory part of the given path names to the
import path only encourages incorrect use of hierarchical names
For example, if my proto file is named api.proto and is not meant to be
imported with a hierarchical name, it is incorrect to allow me to specify it as
`path/to/api.proto` because if I import a second file which happens to import
`api.proto` the parser has no way of knowing that it is supposed to be the same
as `path/to/api.proto` which I originally gave it.
Addresses issue #80

Stop putting directories from the file names onto the import path

---

Gopkg.toml

Use override instead of constraint for dep warning to `k0kubun/pp` package vendering.
Here is the warning log:
```sh
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:
✗  github.com/k0kubun/pp
```

vendor: use override instead of constraint for dep warning to k0kubun/pp

---

adapter/presenter/cli.go

I assume an output has `a_bool` field.
previously, Evans doesn't emit default values like:
``` bash
{
}
```
I modified that behavior to emit default values like:
``` bash
{
"a_bool": false
}
```

Emit default values to an output string

---

adapter/controller/cli.go

When --help was called, help message has a problem with  `--help` and `--version` reorder

fix help output

---

adapter/internal/protoparser/parser.go
adapter/protobuf/message_test.go
adapter/protobuf/parser_test.go
adapter/protobuf/protobuf_test.go

Allow protofiles to be specified by fullpath.
When specifying the `full path`, the current way of "resolving" it add a `.` in front of it, so it will become a `relative path`.
For example: 
`evans --host=localhost --port=8080 --repl /tmp/test/proto/time.proto` will become `evans --host=localhost --port=8080 --repl ./tmp/test/proto/time.proto` so the proto file will be searched relative to the current path.
Signed-off-by: Ricardo Seriani <ricardo.seriani@gmail.com>

Allow protofiles to be specified by fullpath

---

config/config.go

Always set defaults to Request and Input in Config after loading.
fix #142

fix: crash when request or input is missing in config file.

---

.circleci/scripts/create-new-release.bash

To let gomod recognize each release, the release script also pushes "v" prefixed version.

tagging "v" prefixed version when creating a new release

---

adapter/app/app.go
adapter/grpc/grpc.go
adapter/grpc/grpc_test.go
config/config.go
config/testdata/fixtures/create_a_default_global_config_if_both_of_global_and_local_config_are_not_found.golden.toml
config/testdata/fixtures/load_a_global_config_if_local_config_is_not_found.golden.toml
config/testdata/fixtures/load_a_local_config.golden.toml
config/testdata/fixtures/will_be_apply_flags.golden.toml
config/testdata/fixtures/will_be_apply_flags_but_local_config_doesnt_exist.golden.toml
di/dependency.go
meta/meta.go
tests/e2e/cli_test.go

When the common name which is for verifying the certificates returned from the server and a gRPC server FQDN are mismatched, we want to a way to override the server name by a specified value.
Implemented #170.

add --servername option

---

adapter/app/app.go
adapter/app/app_test.go
adapter/cui/cui.go
adapter/cui/option.go
adapter/cui/option_test.go
main.go
tests/e2e/cli_test.go
tests/e2e/repl_helper.go

Thanks for a great tool.
I believe that using the functional option pattern makes `cui.UI` initialization more extensible.
And maybe the arg `nil` for `app.New` is not best solution, right?
If you check out a piece of code and feel pleased, please take this in.
- https://github.com/motemen/gore/blob/master/gore.go#L25-L31
- https://github.com/motemen/gore/blob/master/option.go

use functional option for cui

---

.goreleaser.yml

In the case of some distributions, Evans will be dynamically linked (ref. #177).
To prevent dynamic linking, I added some flags.

add some flags for static linking

---

grpc/grpc.go

This PR fixes #200.
Currently, Evans checks whether the channel state is READY or not and re-connect if the state is not it.
But, in the case of streaming RPCs, the feature didn't work. This PR fixes it.

wake up channels before creating a new connection

---

go.mod
go.sum

The latest `jhump/protoreflect` resolves #197.

update protoreflect to the latest commit hash

---

app/commands.go
app/flag.go
config/config.go
config/testdata/fixtures/apply_some_proto_files_and_paths.golden.toml
e2e/old_cli_test.go

In new interface and v1.0.0, proto files will be specified as `--proto` flags, not arguments. Because specifying proto files are optional.

add --proto flag

---

app/cli_commands.go
app/commands.go
e2e/old_cli_test.go
e2e/testdata/fixtures/teste2e_cli-print_call_command_usage.golden

`--package` and `--service` flags are required for only `repl` command.

move --package and --service flags into repl command

---

app/cli_commands.go
app/commands.go
e2e/cli_test.go
e2e/testdata/fixtures/teste2e_cli-describe_a_message_descriptor.golden
e2e/testdata/fixtures/teste2e_cli-describe_a_method_descriptor.golden
e2e/testdata/fixtures/teste2e_cli-describe_a_service_descriptor.golden
e2e/testdata/fixtures/teste2e_cli-describe_all_service_descriptors.golden
e2e/testdata/fixtures/teste2e_cli-print_call_command_usage.golden
e2e/testdata/fixtures/teste2e_cli-print_desc_command_usage.golden
e2e/testdata/fixtures/teste2e_cli-print_usage_text_to_the_writer.golden
e2e/testdata/fixtures/teste2e_cli-print_usage_text_to_the_writer_(common_flag).golden
go.mod
go.sum
idl/idl.go
idl/idl_test.go
idl/proto/proto.go
mode/cli.go
repl/mock_test.go
usecase/format_descriptor.go
usecase/format_service_descriptors.go
usecase/get_type_descriptor.go

This PR is a part of #189 
Evans now supports descriptor inspection from CLI mode.
This feature is highly inspired by `grpc_cli` and `grpcurl`.
See `$ evans cli desc -h` for the usage and more detail.

implement desc cli command

---

e2e/cli_test.go
e2e/repl_test.go
e2e/testdata/fixtures/teste2e_cli-call_failure_unary_rpc_with_--enrich_and_json_format.golden
e2e/testdata/fixtures/teste2e_cli-call_failure_unary_rpc_with_--enrich_flag.golden
e2e/testdata/fixtures/teste2e_cli-call_failure_unary_rpc_with_--enrich_flag_against_to_grpc-web_server.golden
e2e/testdata/fixtures/teste2e_cli-call_unary_rpc_with_--enrich_flag.golden
e2e/testdata/fixtures/teste2e_cli-call_unary_rpc_with_--enrich_flag_against_to_grpc-web_server.golden
e2e/testdata/fixtures/teste2e_repl-call_unary_by_selecting_package_and_service_with_enriched_output.golden
e2e/testdata/fixtures/teste2e_repl-call_unaryheadertrailerfailure_by_selecting_package_and_service_with_enriched_output.golden
format/curl/curl.go
format/format.go
format/format_test.go
format/json/json.go
go.mod
go.sum
usecase/call_rpc.go

Evans now supports status details (e.g. `errdetails`).
`call` command with `--enrich` flag displays status details if it was sent.

status details support

---

README.md
e2e/testdata/fixtures/teste2e_repl-call_--help.golden
fill/filler.go
fill/proto/interactive_filler.go
fill/proto/interactive_filler_test.go
repl/commands.go
usecase/call_rpc.go

see Issue: https://github.com/ktr0731/evans/issues/279

Enhancement: in REPL mode allow user to specify path to file for bytes field

---

usecase/call_rpc.go

Fix #291 
- Add `grpc-timeout` header to unary calls and server streaming calls
Let me know for any improvements. Thank you!

feat: add grpc-timeout to unary and server streaming calls

---

grpc/grpc.go
grpc/grpc_test.go
grpc/grpcreflection/reflection.go
grpc/web.go
grpc/web_test.go
mode/common.go
usecase/header_test.go

Fixes #347 
So we just run into this problem. We have several services behind traefik and we distinguish between them by their service/package. However, because reflection runs on its own service/package namespace this doesn't work as there is no way of telling which service it's supposed to be querying to. To solve that we added a header to redirect to one service or another but evans doesn't pass the specified header to the reflection clients.
This PR takes the headers specified via the command line and passes them to the reflection clients, it doesn't introduce any new flag or modify any other behavior.
Not sure if this is how you wanted to solve this problem or if someone is working on this already but as I needed something quick I figured I'd fixed and open a PR to kick the …

pass headers to reflection client

---

.gitignore
.goreleaser.yml

See deprecation notices in GoReleaser for more details.
https://goreleaser.com/deprecations/#brewsgithub

use new GoReleaser format

---

grpc/grpcreflection/reflection.go

This relates to #351.
Unfortunately when addressing the comments I didn't test the changes as they seemed innocuous enough, however, it seems that they broke something internal to the GRPC protocol.
At least with traefik, when sending headers to the reflection client with evans 0.9.2 you get the following error message:
```
evans: failed to run REPL mode: failed to instantiate a new spec: failed to instantiate the spec: failed to list packages by gRPC reflection: failed to list services from reflecton enabled gRPC server: rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR
```
On traefik side you can see:
```
server.go:648: http2: server connection error from X.Y.Z.A:58312: connection error: PROTOCOL_ERROR
```
To be honest, I am not sure I …

fix PROTOCOL_ERROR when sending headers to reflection client

---

README.md

The official doc says:
https://golang.org/doc/go-get-install-deprecation
> Starting in Go 1.17, installing executables with go get is deprecated. 
In order to use "go install", the requirement of the minimum version should also be updated. (v1.13 -> v1.16)
I think this change will help users who prefer using `go install` to brew tap.

go install instead of go get

---

fill/proto/interactive_filler.go
prompt/prompt.go

For multiple fields of the same enum type in a proto message, it's confusing not to prompt which field to enter...
After the change:

add prefix for enum type

---

fill/proto/interactive_filler.go
fill/proto/interactive_filler_test.go

The current implementation resolves the enum value in REPL with the index of selection; It only works if the entries are numbered continuously and zero-based.
If we select `BRAVO`, for instance, the request object is created with a value of `1` in both cases.
```proto
enum Foo {
ALPHA = 0;
BRAVO = 1;
CHARLIE = 2;
DELTA = 3;
}
```
```proto
enum Foo {
ALPHA = 2;
BRAVO = 3;
CHARLIE = 5;
DELTA = 8;
}
```

Resolve enum selection with the field number

---

.github/workflows/main.yml
Makefile
idl/proto/proto.go

Reverts ktr0731/evans#544. This fixes #565.
The changes will be applied when merging https://github.com/ktr0731/evans/pull/546.

Revert "fix to register file descriptors and message descriptors"

---

fill/filler.go

Came across this message myself because of accidental invalid JSON format and this is also consistent with code comment in fill/silent_filler.go#L22

Extend the error message to give hint to user about reason for error

---

README.md

The copy button copies the command prompt. We should remove the command prompt so that what is copied is valid.
I.e. I should be able to click on the "copy" icon and paste directly to the terminal. What is entered in that terminal should be a valid command.

Remove prompt in the instructions to copy valid command

---

README.md

I got a following error message in the previous way to start REPL.
```
% evans repl path/to/api.proto
evans 0.10.9
Usage: evans [global options ...] repl [options ...]
Options:
--package string        default package
--service string        default service
--help, -h              display help text and exit (default "false")
evans: invalid config condition: 1 error occurred:
* one or more proto files, or gRPC reflection required
```

Fix how to start REPL on README

---

README.md
e2e/old_repl_test.go
e2e/repl_test.go
e2e/testdata/fixtures/teste2e_oldrepl-call_unarybytes_(fallback).golden
e2e/testdata/fixtures/teste2e_oldrepl-call_unarybytes_--bytes-as-base64.golden
e2e/testdata/fixtures/teste2e_oldrepl-call_unarybytes_--bytes-as-quoted-literals.golden
e2e/testdata/fixtures/teste2e_repl-call_--help.golden
e2e/testdata/fixtures/teste2e_repl-call_unarybytes_(fallback).golden
e2e/testdata/fixtures/teste2e_repl-call_unarybytes_--bytes-as-base64.golden
e2e/testdata/fixtures/teste2e_repl-call_unarybytes_--bytes-as-quoted-literals.golden
fill/filler.go
fill/proto/interactive_filler.go
fill/proto/interactive_filler_test.go
repl/commands.go
usecase/call_rpc.go

As per https://github.com/ktr0731/evans/pull/611#issuecomment-1418606068, this keeps thing symmetrical with the output, and how grpcurl handles it as well.
The old quoted literal behaviour is still accessible via `--bytes-as-quoted-literals`.

Accept bytes as base64-encoded string by default

---

config/testdata/fixtures/create_a_default_global_config_if_both_of_global_and_local_config_are_not_found.golden.toml
e2e/testdata/fixtures/teste2e_cli-print_call_command_usage.golden
e2e/testdata/fixtures/teste2e_cli-print_desc_command_usage.golden
e2e/testdata/fixtures/teste2e_cli-print_list_command_usage.golden
e2e/testdata/fixtures/teste2e_cli-print_usage_text_to_the_writer.golden
e2e/testdata/fixtures/teste2e_cli-print_usage_text_to_the_writer_(common_flag).golden
meta/meta.go

These are the same changes in v0.10.10, but re-create a new release since it seems like Homebrew tap is broken.

bump to v0.10.11
